SELECT COUNT(*)
FROM Product;

SELECT COUNT(purchase_price)
FROM Product;

CREATE TABLE NULLTbl
(
    col_1 CHAR
);

BEGIN TRANSACTION;

INSERT INTO NULLTbl VALUES (NULL);
INSERT INTO NULLTbl VALUES (NULL);
INSERT INTO NULLTbl VALUES (NULL);

COMMIT;

SELECT COUNT(*), COUNT(col_1)
FROM NULLTbl;